### ISSUE TITLE
unable to set traceid

### ISSUE THREAD

**Issue by bandrea83** [haproxytech/spoa-opentracing#1]
i'm able to read from request headers the x-b3-traceid attribute and use it for unique-id-format. If i print with tags it is displayed correctly, but if i configure as id (args id=unique-id in spoe config file) it is completally ignored. I need it for send span to an already create trace

Also setting unique-id-format as a string it is ignored

**Comment by zaga00** [comment]
Hello @bandrea83,

to add new spans to an existing trace, a span context must be used, which is not supported in the program.  It is also written in the chapter "8. Known bugs and limitations" in the README file:

"The program does not support writing/reading span context, ie you cannot use the program to add spans to an already created trace from another service."

If you use the open source version of HAproxy, then for your needs you can use the opentracing filter, which is located in the directory contrib/opentracing.  That filter has a lot more features than spoa-opentracing program.

The 'id' argument in the 'spoe-message' section is used internally in the program and it is not advisable to change it.

**Comment by aiharos** [comment]
Marking as closed.
